amazon/urls.py
from django.urls import path
from . import views

app_name = "amazon"

urlpatterns = [
    path("", views.index, name="index"),
    path("cadastro", views.cadastro, name="cadastro"),
    path("login", views.login_view, name="login"),
    path("logout",views.logout_view, name="logout")
]

e_commerce/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('amazon.urls'))
]

amazon/models.py
from django.db import models

# Create your models here.

amazon/views.py
from django.shortcuts import render
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login,logout

class CadastroForm(forms.Form):
    nome = forms.CharField(max_length=64, label="Seu Nome:")
    email = forms.EmailField(label="E-mail:")
    senha = forms.CharField(label="Senha:", widget=forms.PasswordInput(), min_length=6)
    confirmar_senha =forms.CharField(label="Confirmar senha:",widget=forms.PasswordInput(), min_length=6)

class LoginForm(forms.Form):
    usuario = forms.CharField(max_length=64,label="Username:")
    senha = forms.CharField(label="Senha:", widget=forms.PasswordInput(),min_length=6)

# Create your views here.
def index(request):
    if "usuario" not in request.session:
        request.session["usuario"] = None
    return render(request, "amazon/index.html", {"session": request.session})

def cadastro(request):
    if request.method == "POST":
        form = CadastroForm(request.POST)
        if form.is_valid():
            senha = form.cleaned_data["senha"]
            confirmar_senha = form.cleaned_data["confirmar_senha"]
            if senha == confirmar_senha:
                nome = form.cleaned_data["nome"]
                email = form.cleaned_data["email"]
                usuario = User.objects.create_user(nome, email, senha)
                usuario.save()
                return HttpResponseRedirect(reverse("amazon:login"))
            else:
                return render(request, "amazon/cadastro.html",{
                    "mensagem": "As senhas não são iguais"
                })
    return render(request, "amazon/cadastro.html",{
        "form": CadastroForm
    })
            

def login_view(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            usuario = form.cleaned_data["usuario"]
            senha = form.cleaned_data["senha"]
            user = authenticate(request, username=usuario, password=senha)
            if user is not None:
                login(request,user)
                request.session["usuario"] = usuario.capitalize()
                return HttpResponseRedirect(reverse("amazon:index"))
            else: 
                return render(request,"amazon/login.html",{
                    "mensagem": "Usuário ou senha estão errados"
                })
            
    return render(request, "amazon/login.html", {
        "form": LoginForm()
    })

def logout_view(request):
    logout(request)
    request.session["usuario"] = None
    return HttpResponseRedirect(reverse("amazon:index"))

amazon/templates/amazon/cadastro.html
{%extends "amazon/layout.html" %}
{%block title%}
<title>Amazon | Cadastro</title>
{%endblock%}

{%block body%}
{%if mensagem%}
    <h4>{{mensagem}}</h4>
{%endif%}
    <form action="{%url 'amazon:cadastro'%}" method="post">
        {%csrf_token%}
        {{form}}
        <input type="submit" value="Cadastrar">
    </form>

{%endblock%}

amazon/templates/amazon/index.html
{% extends "amazon/layout.html"%} {% block title%}
<title>Amazon | Home</title>
{%endblock%} {% block body %}

<body>
    {% if session.usuario != None %}
    <h1>Olá, {{session.usuario}}!</h1>
    <a href="{%url 'amazon:logout'%}">Sair</a>
    {% else %}
    <h1>Olá, visitante!</h1>
    <a href="{% url 'amazon:login'%}">Olá, Faça seu login</a> {% endif %}
</body>
{%endblock%}

amazon/templates/amazon/layout.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta chaset="utf-8"> {% block title %} {% endblock %}
</head>

<body>
    {% block body%} {% endblock %}
</body>

</html>

amazon/templates/amazon/login.html
{% extends 'amazon/layout.html'%}{% block title%}
<title>Amazon | Login</title>
{% endblock %} {% block body%}

    <h1>Login</h1>
    {%if mensagem%}
        <h4>{{mensagem}}</h4>
    {%endif%}
    <form action="{% url 'amazon:login'%}" method="post">
        {%csrf_token%}{{form}}
        <input type="submit" value="Login">
    </form>
    <a href="{%url 'amazon:cadastro'%}">Ainda não tem uma conta? Cadastre-se</a>
{% endblock%}